### PR TITLE
csmdb_migration_script_16_1_with_ssd_inventory_support

### PR DESCRIPTION
**Pull request by williammorrison2**
16.1 migration script along with
Update 'fn_csm_ssd_dead_records' and 'fn_csm_ssd_history_dump'
now clean up any lvs and vgs on an ssd before we delete the ssd from table.

### CODE REVIEW

**Comment by NickyDaB** [comment]
```
[root@c650f03p41 bin]# ./csm_bb_vg_create -a 0 -n "n02" -s "ssd_002" -S 250 -t 250 -V "vg_02" -c t
---
# The vg: "vg_02" has been successfully created on node: "n02".
...
[root@c650f03p41 bin]# ./csm_bb_vg_create -a 0 -n "n02" -s "ssd_002" -S 250 -t 250 -V "vg_03" -c f
---
# The vg: "vg_03" has been successfully created on node: "n02".
...
[root@c650f03p41 bin]# ./csm_bb_lv_create -a 1 -c 0 -f "mount" -F "type" -l "lv_01" -n "n02" -s C -V "vg_02"
---
# The lv: "lv_01" has been successfully created on node: "n02" for allocation_id: 1.
...

```

**Comment by NickyDaB** [comment]
we made multiple vgs on an ssd. one of the vgs we created a lv.

we did this to check for both vgs with content and vgs without content. 

we want to make sure the ssd and related tables are all properly cleaned up

**Comment by pdlun92** [comment]
This pull request passes:
- Regression
- Unit testing on the migration script
- Unit testing on the ssd cascading delete
- Unit testing on the switch inventory / updating

So I am approving these changes.  However I do have some questions that are more in the general design area, specifically related to the cascading ssd deletion.  I know we've talked a lot about it recently but having gone through unit testing, hopefully we can discuss once more on monday @williammorrison2  @fpizzano @besawn

**Comment by pdlun92** [comment]
New changes look good as well. Regression passes, as well as 2 new unit test cases for 

1) creating 2 ssd's, creating 1 vg per ssd, inserting the same ssd's with swapped serial/node name pairs, forcing inventory collection and observing the expected cascading deletes
2) creating an allocation, creating an LV on that allocation, deleting the allocation and observing the cascading delete on the LV

Approving (again)

**Pull request merged**
