### PR TITLE
Issues/770 csm allocation step query details segmentation fault

### PR DESCRIPTION
**Pull request by NickyDaB**
# Purpose
To fix issue https://github.com/IBM/CAST/issues/770 but not having the cmd line api seg fault. 

# Approach
I decided to go with: 
- don't leave out any data from the user.
- show them all records that matched the query, even if there are multiple steps with the same step id in that allocation. which will probably never happen in production.

# Origin
https://github.com/IBM/CAST/issues/770

@fpizzano  found an issue. very rare edge case. will probably never happen in production. where if there are multiple steps with a matching id under the same allocation, then allocation step query details cmd line interface will segfault. 

# How to Test
_This section will help the regression tester._
1. manually create the situation in a test database.
2. run the api.
3. see if the seg fault still happens. 
4. you can look at https://github.com/IBM/CAST/issues/770 for an example

# Screenshots
screen shots of terminal output are in https://github.com/IBM/CAST/issues/770

### CODE REVIEW

**Comment by williammorrison2** [comment]
@NickyDaB I ran our current FVT regression suite against the PR and it passes. We can run some further unit tests to verify the expected behavior.

**Comment by besawn** [comment]
Before we merge this, I think we should add some tests to the FVT regression buckets that highlight the problem. We should add the tests, run the tests against current master showing that they fail, then run the tests against this PR to confirm that they pass, then we can merge this PR.

@NickyDaB  To test this, were you just able to create an allocation and then create some duplicate steps using the CSM command line APIs or is it more complicated than that to create duplicate steps?

@williammorrison2 If we are able to test using basic CSM commands, I think you should be able to add some additional tests to csmtest/buckets/basic/step.sh to cover this. I think we should try a few different combinations of duplicate steps.

**Comment by NickyDaB** [comment]
> Can you please clean up the temporary printfs and extra comments before we merge this to master? If you want to keep any of the debug statements for future use, please convert them to log messages instead, otherwise we can just remove them.

Yes. I can. Pretty easy to do. I thought about doing it actually. 

I didn't do it in case for some reason we had to go back in the future. I wanted to see what I / how I was debugging it. I read it in a coding technique book last month. They basically recommend to leave any temporary debugging stuff like print fs inside the code. It shows... hey, someone was here before and had to debug this. And if a second coder comes along its a hint as to... maybe this isnt very clear if we are debugging it a second time. and maybe we should look into how this is fundamentally written. 

I didn't include them in the default "print debug" because I don't think they are actually valuable as debug statements. Only valuable as notes to a future dev, that's why i left them as comments. the goal was like, Cliff note: "someone had to debug this before" 

I'd like to leave it in for these reasons, but after reading my post if I didn't convince you, I don't mind removing them. No hard feelings.

**Comment by NickyDaB** [comment]
> To test this, were you just able to create an allocation and then create some duplicate steps using the CSM command line APIs or is it more complicated than that to create duplicate steps?

@besawn I had to manually insert an allocation in my database (because of my environment, i don't believe it is necessary for the test case), i used allocation step begin and end to create and remove the steps after that. So... I think we should be able to do normal API cmds to re create the test case.

**Comment by NickyDaB** [comment]
remove printf comments. left descriptor comments.

**Comment by williammorrison2** [comment]
@NickyDaB @besawn @fpizzano While running some manual and automated tests I noticed a particular combination created a `Segmentation fault`.

I tried to tests some of the combination that others used, but wanted to do some additional tests.

I created the following combinations via csm_allocation_step_begins and csm_allocation_step_ends.
Below is an output of the record combinations in the csmdb.
```
csmdb=> select allocation_id, step_id from csm_step_history;
 allocation_id | step_id
---------------+---------
             1 |       1
             1 |       1
             1 |       1
             1 |       2
             1 |       2
(6 rows)
```
While running
```
[root@c650mnp05 basic]# csm_allocation_step_query_details -a 1 -s 1
---
Total_Records: 3
Record_1:
  allocation_id:        1
  step_id:              1
  argument:             my_argument
  begin_time:           2019-10-16 14:18:39.605536
  status:
  executable:           my_executable
  working_directory:    my_workding_directory
  environment_variable: my_environment_variable
  num_nodes:            1
  num_processors:       1
  num_gpus:             1
  projected_memory:     512
  num_tasks:            1
  user_flags:
  compute_nodes:
    - c650f99p18
  history:
    archive_history_time:
    cpu_stats:            cpu_good
    end_time:             2019-10-16 14:18:44.977348
    error_message:        error
    exit_status:          1
    gpu_stats:            gpu_s_good
    io_stats:             io_sts_good
    max_memory:           512
    memory_stats:         mem_sts_good
    omp_thread_limit:     t_num_threads_good
    total_s_time:         0.000000
    total_u_time:         0.000000
Record_2:
  allocation_id:        1
  step_id:              1
  argument:             my_argument
  begin_time:           2019-10-16 14:18:53.431965
  status:
  executable:           my_executable
  working_directory:    my_workding_directory
  environment_variable: my_environment_variable
  num_nodes:            1
  num_processors:       1
  num_gpus:             1
  projected_memory:     512
  num_tasks:            1
  user_flags:
  compute_nodes:
    - c650f99p18
  history:
    archive_history_time:
    cpu_stats:            cpu_good
    end_time:             2019-10-16 14:18:55.986543
    error_message:        error
    exit_status:          1
    gpu_stats:            gpu_s_good
    io_stats:             io_sts_good
    max_memory:           512
    memory_stats:         mem_sts_good
    omp_thread_limit:     t_num_threads_good
    total_s_time:         0.000000
    total_u_time:         0.000000
Record_3:
  allocation_id:        1
  step_id:              1
  argument:             my_argument
  begin_time:           2019-10-16 14:18:58.310625
  status:
  executable:           my_executable
  working_directory:    my_workding_directory
  environment_variable: my_environment_variable
  num_nodes:            1
  num_processors:       1
  num_gpus:             1
  projected_memory:     512
  num_tasks:            1
  user_flags:
  compute_nodes:
    - c650f99p18
  history:
    archive_history_time:
    cpu_stats:            cpu_good
    end_time:             2019-10-16 14:18:59.74584
    error_message:        error
    exit_status:          1
    gpu_stats:            gpu_s_good
    io_stats:             io_sts_good
    max_memory:           512
    memory_stats:         mem_sts_good
    omp_thread_limit:     t_num_threads_good
    total_s_time:         0.000000
    total_u_time:         0.000000
...
```
But when I try this combination (below) I get the `segmentation fault`
```
[root@c650mnp05 basic]# csm_allocation_step_query_details -a 1 -s 2
---
Total_Records: 2
Record_1:
  allocation_id:        1
  step_id:              2
  argument:             my_argument
  begin_time:           2019-10-16 14:21:55.504792
  status:
  executable:           my_executable
  working_directory:    my_workding_directory
  environment_variable: my_environment_variable
  num_nodes:            1
  num_processors:       1
  num_gpus:             1
  projected_memory:     512
  num_tasks:            1
  user_flags:
  compute_nodes:
Segmentation fault
```

### Here are the steps I followed (manually to recreate)
1. Created the allocation
`$ csm_allocation_create -j 1 -n <compute_node_here>`

2. Created a step using the specific allocation then deleted the step
`$ csm_allocation_step_begin --step_id 1 --allocation_id 1 --executable "my_executable" --working_directory "my_workding_directory" --argument "my_argument" --environment_variable "my_environment_variable" --num_processors 1 --num_gpus 1 --projected_memory 512 --num_tasks 1 --compute_nodes <compute_node_here>`
`$ csm_allocation_step_end -a 1 -s 1 -e 1 -E "error" -c "cpu_good" -t 0.0 -T 1.5 -n "t_num_threads_good" -G "gpu_s_good" -m "mem_sts_good" -M 512 -i "io_sts_good"`

3. Created another step using the same step_id of the previous process then deleted the step
`$ csm_allocation_step_begin --step_id 1 --allocation_id 1 --executable "my_executable" --working_directory "my_workding_directory" --argument "my_argument" --environment_variable "my_environment_variable" --num_processors 1 --num_gpus 1 --projected_memory 512 --num_tasks 1 --compute_nodes <compute_node_here>`
`$ csm_allocation_step_end -a 1 -s 1 -e 1 -E "error" -c "cpu_good" -t 0.0 -T 1.5 -n "t_num_threads_good" -G "gpu_s_good" -m "mem_sts_good" -M 512 -i "io_sts_good"`

4. Created yet another step using the same step_id of the previous processes then deleted the step
`$ csm_allocation_step_begin --step_id 1 --allocation_id 1 --executable "my_executable" --working_directory "my_workding_directory" --argument "my_argument" --environment_variable "my_environment_variable" --num_processors 1 --num_gpus 1 --projected_memory 512 --num_tasks 1 --compute_nodes <compute_node_here>`
`$ csm_allocation_step_end -a 1 -s 1 -e 1 -E "error" -c "cpu_good" -t 0.0 -T 1.5 -n "t_num_threads_good" -G "gpu_s_good" -m "mem_sts_good" -M 512 -i "io_sts_good"`

5. Created a new step using the same allocation then deleted the step
`$ csm_allocation_step_begin --step_id 2 --allocation_id 1 --executable "my_executable" --working_directory "my_workding_directory" --argument "my_argument" --environment_variable "my_environment_variable" --num_processors 1 --num_gpus 1 --projected_memory 512 --num_tasks 1 --compute_nodes <compute_node_here>`
`$ csm_allocation_step_end -a 1 -s 2 -e 1 -E "error" -c "cpu_good" -t 0.0 -T 1.5 -n "t_num_threads_good" -G "gpu_s_good" -m "mem_sts_good" -M 512 -i "io_sts_good"`

6. Created another step using the same step_id:2 of the previous process then deleted the step
`$ csm_allocation_step_begin --step_id 2 --allocation_id 1 --executable "my_executable" --working_directory "my_workding_directory" --argument "my_argument" --environment_variable "my_environment_variable" --num_processors 1 --num_gpus 1 --projected_memory 512 --num_tasks 1 --compute_nodes <compute_node_here>`
`$ csm_allocation_step_end -a 1 -s 2 -e 1 -E "error" -c "cpu_good" -t 0.0 -T 1.5 -n "t_num_threads_good" -G "gpu_s_good" -m "mem_sts_good" -M 512 -i "io_sts_good"`

7. Then I ran csm_allocation_step_query_details on the combinations (output results above).
`$ csm_allocation_step_query_details -a 1 -s 1`
`$ csm_allocation_step_query_details -a 1 -s 2`

An additional combination which `Seg faulted` when I created (steps 1,2,3,1,2,3,1,2,3).
(These were done in sequence one at a time using csm_allocation_step_begin then calling csm_allocation_step_end) <-------- Don't want to create too much clutter with all those combos :-)
Below is the details using the combination of allocation_id 3 and the step combos from above.
```
csmdb=> select allocation_id, step_id from csm_step_history;
 allocation_id | step_id
---------------+---------
             3 |       1
             3 |       2
             3 |       3
             3 |       1
             3 |       2
             3 |       3
             3 |       1
             3 |       2
             3 |       3
(9 rows)
```

**Comment by NickyDaB** [comment]
I decided to change the way this edge case is handled.

```
[root@c650f03p41 bin]# ./csm_allocation_step_query_details -a 1 -s 1
---
Total_Records: 3
# Error: There should only be one matching step record. Verify the database. 
[root@c650f03p41 bin]#
```

**Comment by williammorrison2** [comment]
I pulled in @NickyDaB your new changes and while building I got the following error:
```
[ 71%] Built target csmras
[ 71%] Building CXX object csmd/src/daemon/src/CMakeFiles/csmd.dir/csmi_request_handler/CSMIAllocationStepQueryDetails.cc.o
/u/wcmorris/CAST/csmd/src/daemon/src/csmi_request_handler/CSMIAllocationStepQueryDetails.cc: In member function ‘virtual bool CSMIAllocationStepQueryDetails::CreateByteArray(const std::vector<csm::db::DBTuple*>&, char**, uint32_t&, csm::daemon::EventContextHandlerState_sptr&)’:
/u/wcmorris/CAST/csmd/src/daemon/src/csmi_request_handler/CSMIAllocationStepQueryDetails.cc:462:62: error: ‘elseif’ was not declared in this scope
     }elseif(step_count > 0  && output->num_steps < step_count)
                                                              ^
/u/wcmorris/CAST/csmd/src/daemon/src/csmi_request_handler/CSMIAllocationStepQueryDetails.cc:463:5: error: expected ‘;’ before ‘{’ token
     {
     ^
/u/wcmorris/CAST/csmd/src/daemon/src/csmi_request_handler/CSMIAllocationStepQueryDetails.cc:631:1: error: expected ‘}’ at end of input
 }
 ^
/u/wcmorris/CAST/csmd/src/daemon/src/csmi_request_handler/CSMIAllocationStepQueryDetails.cc:631:1: error: no return statement in function returning non-void [-Werror=return-type]
cc1plus: all warnings being treated as errors
make[2]: *** [csmd/src/daemon/src/CMakeFiles/csmd.dir/csmi_request_handler/CSMIAllocationStepQueryDetails.cc.o] Error 1
make[1]: *** [csmd/src/daemon/src/CMakeFiles/csmd.dir/all] Error 2
make: *** [all] Error 2
*** CONFIGURE FAILED  (cmd= make package noinstall   rc=512)
```

**Comment by NickyDaB** [comment]
I'll look into it. Maybe I forgot to upload a file change. seems like a typo based off your output

**Pull request merged**
