### PR TITLE
Fixed the sign of the number of nodes in the allocation step structs.

### PR DESCRIPTION
**Pull request by mew2057**
Issue  #23:

Looks like the sign of the `num_nodes` for `csmi_allocation_step_t` and `csmi_allocation_step_mcast_context` was missed a while back. This fix needs to be pulled in, but JSM might break without the new headers.

@fpizzano can you contact JSM before this is merged in?

### CODE REVIEW

**Comment by mew2057** [comment]
I should note this breaks the "promise" of versioning, but this is glaring enough of a miss/directly breaks builds that I think it's worth doing.

**Comment by NickyDaB** [comment]
Hmm. Is this field related to the field "num_nodes" in the "csm_step" table of the CSM Database?

**Comment by NickyDaB** [comment]
If this struct is supposed to represent a "database record" then I'm not 100% sure if we should change this value from signed to unsigned. 

The rest of this comment is under the condition that this struct is a 1:1 match to a database record for "csm_step".  

Potential concerns:  
- The database represents it as signed. If we change this value in the struct it could lead to situations with bad data representation. 
- If this is input into the database, then the API can do a check when it is called to see if the value is less than zero. Handle any errors here.
- If this is an output from the database, then I suggest to keep the data the same and present whatever the data is in the database. Even if this means a negative number. 

If this is not a struct that is supposed to match the database record, then I'm not sure if I'm feeling as strongly that it needs to stay consistent with the database.

**Comment by mew2057** [comment]
Looking at this again, I think only the internal struct should be changed.

**Comment by mew2057** [comment]
I think this should be good now, if you want to take a look. This shouldn't require any changes to any external users of the APIs.

**Comment by mew2057** [comment]
I've been reviewing this and there is a slight concern I now have: in serialization we use the field to key array size. If it's unsigned it's technically possible that the size of the array become the unsigned maximum if a -1 were placed in the field. Maybe we need to add a secondary field used under the hood which tracks the size of the array in an unsigned manner?

**Comment by NickyDaB** [comment]
> I've been reviewing this and there is a slight concern I now have: in serialization we use the field to key array size. If it's unsigned it's technically possible that the size of the array become the unsigned maximum if a -1 were placed in the field. Maybe we need to add a secondary field used under the hood which tracks the size of the array in an unsigned manner? : @mew2057 

That sounds reasonable. I sometimes take that approach on some of the inventory APIs. I usually add extra values called "arrayName_count" for those. even if there is a "num_whatever" in the database that technically represents that same number value.

**Pull request merged**
