### PR TITLE
synchronized environmental data collection

### PR DESCRIPTION
**Pull request by lasch**
This PR changes the scheduling of environmental data collection from being based on daemon start time to being based on the beginning of the epoch (i.e. a common fixed point of time in the past).

Assuming synchronized time between compute nodes, this will help to collect the data of one configured bucket at the same time across the whole set of compute nodes.

Note that this is only addressing the synchronized data collection and will cause a burst of messages arriving at the service nodes and the BDS.

In my limited test environment, I could see the effect by looking at the time stamps of environmental data activity. I set the interval of a bucket to 15s and the events always were happening at offsets 00, 15, 30, and 45s regardless of the start time of the daemon. And I could only use the debug/dummy environmental data source here. So it needs testing in a proper environment where actual data collection and multiple compute nodes are available.

So far, the output in the logs suggests that it does what it's supposed to do:
```
[COMPUTE]2019-02-27 17:30:31.239573       csmd::info     | CSMD: COMPUTE; Version: 1.6.0; Build: 9da375d618; Date: Tue Feb 26 15:27:50 2019 -0500; Config file: ./myconfigB/csm_compute.cfg
...<note: 14s between daemon start and first scheduled ENV event>
[COMPUTE]2019-02-27 17:30:45.000179       csmd::debug    | CSMD_MAIN: ==== [5] event_type=EVENT_TYPE_ENVIRONMENTAL handler=CSM_ENVIRONMENTAL ====
[COMPUTE]2019-02-27 17:31:00.000196       csmd::debug    | CSMD_MAIN: ==== [6] event_type=EVENT_TYPE_ENVIRONMENTAL handler=CSM_ENVIRONMENTAL ====
[COMPUTE]2019-02-27 17:31:15.000189       csmd::debug    | CSMD_MAIN: ==== [8] event_type=EVENT_TYPE_ENVIRONMENTAL handler=CSM_ENVIRONMENTAL ====



[COMPUTE]2019-02-27 17:32:10.576368       csmd::info     | CSMD: COMPUTE; Version: 1.6.0; Build: 9da375d618; Date: Tue Feb 26 15:27:50 2019 -0500; Config file: ./myconfigB/csm_compute.cfg
... <note: just 5s between start and first scheduled ENV event>
[COMPUTE]2019-02-27 17:32:15.000178       csmd::debug    | CSMD_MAIN: ==== [5] event_type=EVENT_TYPE_ENVIRONMENTAL handler=CSM_ENVIRONMENTAL ====
[COMPUTE]2019-02-27 17:32:30.000157       csmd::debug    | CSMD_MAIN: ==== [6] event_type=EVENT_TYPE_ENVIRONMENTAL handler=CSM_ENVIRONMENTAL ====
[COMPUTE]2019-02-27 17:32:45.000158       csmd::debug    | CSMD_MAIN: ==== [7] event_type=EVENT_TYPE_ENVIRONMENTAL handler=CSM_ENVIRONMENTAL ====
```

### CODE REVIEW

**Comment by pdlun92** [comment]
First round of testing on this change looks good.  For this test, one compute has an altered system clock, started the deamons at approximately the same "real" time using default configs (10 min timer):

```
[COMPUTE]2019-02-28 04:53:54.626934       csmd::info     | INV_AGENT_HANDLER: CONNECT event. Re-/sending node inventory to: 10.7.3.13:9800
[COMPUTE]2019-02-28 04:53:54.626959       csmd::info     | CONN_CTRL_HANDLER: Processing: EVENT_TYPE_SYSTEM
[COMPUTE]2019-02-28 05:00:00.000143     csmenv::info     | Built without DCGM support, GPU related functions are disabled.
[COMPUTE]2019-02-28 05:00:00.000225     csmenv::warning  | Built without DCGM support, skipping CollectGpuData()
[COMPUTE]2019-02-28 05:00:00.000330     csmenv::warning  | ResetOccCsmSensorMinMax() failed.
[COMPUTE]2019-02-28 05:10:00.000148     csmenv::warning  | Built without DCGM support, skipping CollectGpuData()
[COMPUTE]2019-02-28 05:10:00.000235     csmenv::warning  | ResetOccCsmSensorMinMax() failed.
[COMPUTE]2019-02-28 05:20:00.000133     csmenv::warning  | Built without DCGM support, skipping CollectGpuData()
[COMPUTE]2019-02-28 05:20:00.000249     csmenv::warning  | ResetOccCsmSensorMinMax() failed.
[COMPUTE]2019-02-28 05:30:00.000121     csmenv::warning  | Built without DCGM support, skipping CollectGpuData()
[COMPUTE]2019-02-28 05:30:00.000203     csmenv::warning  | ResetOccCsmSensorMinMax() failed.
[COMPUTE]2019-02-28 05:40:00.000110     csmenv::warning  | Built without DCGM support, skipping CollectGpuData()
[COMPUTE]2019-02-28 05:40:00.000200     csmenv::warning  | ResetOccCsmSensorMinMax() failed.
```
```
[COMPUTE]2019-02-28 13:14:53.078111       csmd::info     | INV_AGENT_HANDLER: CONNECT event. Re-/sending node inventory to: 10.7.3.13:9800
[COMPUTE]2019-02-28 13:20:00.000143     csmenv::info     | Built without DCGM support, GPU related functions are disabled.
[COMPUTE]2019-02-28 13:20:00.000183     csmenv::warning  | Built without DCGM support, skipping CollectGpuData()
[COMPUTE]2019-02-28 13:20:00.000289     csmenv::warning  | ResetOccCsmSensorMinMax() failed.
[COMPUTE]2019-02-28 13:30:00.000152     csmenv::warning  | Built without DCGM support, skipping CollectGpuData()
[COMPUTE]2019-02-28 13:30:00.000255     csmenv::warning  | ResetOccCsmSensorMinMax() failed.
[COMPUTE]2019-02-28 13:40:00.000154     csmenv::warning  | Built without DCGM support, skipping CollectGpuData()
[COMPUTE]2019-02-28 13:40:00.000265     csmenv::warning  | ResetOccCsmSensorMinMax() failed.
```

NOTE: I made this build using docker.  Still experimenting with that process and obviously need to add DCGM support but I think the timestamps are proof enough that the trigger is epoch time dependent

**Comment by lasch** [comment]
> NOTE: I made this build using docker. Still experimenting with that process and obviously need to add DCGM support but I think the timestamps are proof enough that the trigger is epoch time dependent

Just as a side note: in case you want to see 'actualy data' being 'collected' and sent, you can always used the `debug` environmental source. It will send a time stamped message with the hostname as env data to the aggregator. (just in case you want to test on a system that doesn't have any of the other data sources available.)

**Comment by lasch** [comment]
As discussed yesterday, there's more to come for this one to work with situations where the system clock gets adjusted.

**Comment by lasch** [comment]
Added a mechanism that is able to adjust to changes of the system clock.

This is the approach I took:
- I wanted to avoid having to retrieve the system time for each and every scheduling step (reducing the syscall load a little bit)
- so each bucket keeps track of how long ago it has been checked/adjusted
- if that time exceeds a threshold, the next scheduling slot is calculated based on a fresh system time stamp
- (current threshold is set to 60s to make testing easier)

Considerations:
- we might want to make this threshold configurable through the tuning parameter section 1) to allow quick adjustment in the field and 2) to find a good default for the next release

Here's the output from my tests:
```
$ tail -f csm_compute.log | grep ItemSched
[COMPUTE]2019-03-01 10:04:15.000159       csmd::debug    | ItemScheduler: Scheduling of bucketID: 0
[COMPUTE]2019-03-01 10:04:30.000141       csmd::debug    | ItemScheduler: Scheduling of bucketID: 0

   <<< system clock got changed here >>>
  <<< scheduling still happens every 15s, but with timestamps 6s off the interval >>>
[COMPUTE]2019-03-01 10:05:06.000174       csmd::debug    | ItemScheduler: Scheduling of bucketID: 0
[COMPUTE]2019-03-01 10:05:21.000185       csmd::debug    | ItemScheduler: Scheduling of bucketID: 0
[COMPUTE]2019-03-01 10:05:36.000141       csmd::debug    | ItemScheduler: Scheduling of bucketID: 0
[COMPUTE]2019-03-01 10:05:36.000262       csmd::debug    | ItemScheduler: Checking/Adjusting schedule of bucketID: 0

  <<< info-msg: scheduling interval is adjusted (6s shorter) >>>
[COMPUTE]2019-03-01 10:05:36.000285       csmd::info     | ItemScheduler: (system clock changed) adjusting next slot for bucketID: 0 from 216 to 210

  <<< re-aligned data collection >>>
[COMPUTE]2019-03-01 10:05:45.000124       csmd::debug    | ItemScheduler: Scheduling of bucketID: 0
[COMPUTE]2019-03-01 10:06:00.000143       csmd::debug    | ItemScheduler: Scheduling of bucketID: 0
[COMPUTE]2019-03-01 10:06:15.000131       csmd::debug    | ItemScheduler: Scheduling of bucketID: 0
```

**Comment by pdlun92** [comment]
I've gotten a successful regression run on this guy with all the latest changes, as well as a successful manual test case of system clock adjustment on a compute:

```
# grep "node environmental data collection was successful" csm_compute.log._c650f99p36
[COMPUTE]2019-03-13 14:11:00.027310     csmenv::info     | CSM_ENVIRONMENTAL environmental: node environmental data collection was successful.
[COMPUTE]2019-03-13 14:12:00.028441     csmenv::info     | CSM_ENVIRONMENTAL environmental: node environmental data collection was successful.
[COMPUTE]2019-03-13 14:11:19.025751     csmenv::info     | CSM_ENVIRONMENTAL environmental: node environmental data collection was successful.
[COMPUTE]2019-03-13 14:12:19.022880     csmenv::info     | CSM_ENVIRONMENTAL environmental: node environmental data collection was successful.
[COMPUTE]2019-03-13 14:13:00.020181     csmenv::info     | CSM_ENVIRONMENTAL environmental: node environmental data collection was successful.
[COMPUTE]2019-03-13 14:14:00.025329     csmenv::info     | CSM_ENVIRONMENTAL environmental: node environmental data collection was successful.

# grep ItemSched csm_compute.log._c650f99p36
[COMPUTE]2019-03-13 14:12:19.000862       csmd::info     | ItemScheduler: (system clock changed) adjusting next slot for bucketID: 0 from 26 to 7
[COMPUTE]2019-03-13 14:12:19.001000       csmd::info     | ItemScheduler: (system clock changed) adjusting next slot for bucketID: 1 from 26 to 7
```
from master point of view
```
# grep "Received ssd wear update from c650f99p36" /var/log/ibm/csm/csm_master.log
2019-03-13 14:11:00.044140       csmd::info     | SSD_WEAR: NEW EVENT: Received ssd wear update from c650f99p36, discovered_ssds=0
2019-03-13 14:12:00.038911       csmd::info     | SSD_WEAR: NEW EVENT: Received ssd wear update from c650f99p36, discovered_ssds=0
2019-03-13 14:12:59.588691       csmd::info     | SSD_WEAR: NEW EVENT: Received ssd wear update from c650f99p36, discovered_ssds=0
2019-03-13 14:13:59.585938       csmd::info     | SSD_WEAR: NEW EVENT: Received ssd wear update from c650f99p36, discovered_ssds=0
2019-03-13 14:14:40.583533       csmd::info     | SSD_WEAR: NEW EVENT: Received ssd wear update from c650f99p36, discovered_ssds=0
2019-03-13 14:15:40.589088       csmd::info     | SSD_WEAR: NEW EVENT: Received ssd wear update from c650f99p36, discovered_ssds=0
2019-03-13 14:16:40.589866       csmd::info     | SSD_WEAR: NEW EVENT: Received ssd wear update from c650f99p36, discovered_ssds=0
```
@lasch let me know if this looks valid and I will approve

**Pull request merged**
