### PR TITLE
csm: adding initial documentation for daemon and api configuration

### PR DESCRIPTION
**Pull request by lasch**
Added an initial documentation file that explains the settings of the csm config file as well as the ACL and API-cfg. With exclusive focus on the csm section. So there's more to come.

There are a few items that I don't know much about and left them as tbd waiting for the owners to jump in and explain. However, the current status should cover a lot of things already.
I think, it'll need some small input from @NickyDaB to update the csm.inventory section and @besawn to help with the csm.ufm section.

I'm sure it will require some review of the language too.
It's also not yet covering the restd section.

### CODE REVIEW

**Comment by NickyDaB** [comment]
> left them as tbd waiting for the owners to jump in and explain

Sounds good. Lets get these additions in, then I can fill in some of those sections later.

**Comment by besawn** [comment]
Just as an FYI, I think both the ras and ufm blocks are unused.

The ras block is still referenced in some places in the RAS code, but I don't think the configuration settings are used for anything.

I originally added the ufm block to assist a different developer, but it looks like @NickyDaB ended up using csm.inventory instead to accomplish the same purpose. @NickyDaB can you confirm that you aren't aware of any usage of "csm.ufm" in any of your code that interfaces with UFM? I wasn't able to find any examples when I searched.

I will take a todo to review the usage of "csm.ras" and handle any relevant clean up in a future PR. 

I am fine with either omitting "csm.ras" and "csm.ufm" from the current pull request or pushing as-is and cleaning those sections up later.

**Comment by lasch** [comment]
@besawn thanks for the input. How about I prevent duplicate "remove-it" work and leave the ras and ufm sections out of the docs for now?

**Comment by besawn** [comment]
@lasch Sounds good to me.

**Comment by lasch** [comment]
done. removed the 2 sections for now

**Comment by NickyDaB** [comment]
we use the ufm block

**Comment by lasch** [comment]
@NickyDaB do you refer to `csm.inventory.ufm` or to `csm.ufm`?

**Comment by fpizzano** [comment]
We need `csm.ufm`, we are planning to use this section for IB perforamnce counter, diagnostics and health checks.

**Comment by lasch** [comment]
Sorry for removing too quickly, put it back in together with small formatting fixes.

**Pull request merged**
