### PR TITLE
filled in more of CODEOWNERS File

### PR DESCRIPTION
**Pull request by NickyDaB**
# CODEOWNERS File Additions

## Purpose
- filled in to best of my knowledge
- others should contribute to this file if they want ownership over a part of code. This will auto add them in as reviewers as we improve automation of github features. 

## How to Test
1. See if this automation works when new pull requests are opened.

### CODE REVIEW

**Comment by lasch** [comment]
Very good. I was about to add myself to csmnet and csmd. csmconf is fine for me too.

Quick question. You mention in a comment that Bill and Pat should be added to everything for testing (until automated) but have not actually created that policy (unless I missed it). Was that on purpose or by accident?

**Comment by NickyDaB** [comment]
@lasch 

> Quick question. You mention in a comment that Bill and Pat should be added to everything for testing (until automated) but have not actually created that policy (unless I missed it). Was that on purpose or by accident?

Yeah, I wasn't sure if I wanted to automate that. My thinking was that, they aren't really the "codeowner" so if someone sees the codeowner file, looking to contact someone, then they might accidentally email bill when they should have emailed lars for questions about CSM Infrastructure. (but eventually I think it will be more obvious that a git status checker bot is not a code author that can be emailed to ask about code) So for now, i left them out of the automated code owner file. but we can still add them as reviewers manually to the pull request. 


> Was that on purpose or by accident?

on purpose, I also added in `maybe?` to that comment. trying to show my undecidedness. 

But I also wanted to hear others thoughts. like, we could add them into every field, and they would be automated into reviewers on pull requests.

**Comment by tgooding** [comment]
I'd suggest removing the file type experts.  I doubt John wants to review the python in burst buffer component.  The enclosing directory ownership should be sufficient.

**Comment by NickyDaB** [comment]
@tgooding 

> I'd suggest removing the file type experts. I doubt John wants to review the python in burst buffer component. The enclosing directory ownership should be sufficient.

Sure. Sounds good. I just took a guess at some things here.  I'll let @mew2057 decide if he wants to do that or not. @williammorrison2 specifically requested to review all sql files. So I'll leave that one still in there.

**Comment by mew2057** [comment]
Yeah I don't want to be notified for every python change.

**Comment by NickyDaB** [comment]
ok, i'll update

**Comment by NickyDaB** [comment]
@tgooding and @mew2057 

updates pushed, good to approve?

**Pull request merged**
