### PR TITLE
Bds fvt

### PR DESCRIPTION
**Pull request by NickyDaB**
# Purpose
Include some FVT test cases to validate that python scripts for CAST BDS still work whenever a code change is made. 

# Approach
- followed existing patterns and templates.
- asked @mew2057 for opinions and help along the way (BDS)
- asked @williammorrison2  for opinions and help along the way (FVT)
- tested with @williammorrison2 to prove working

# Origin
N/A

# How to Test
1. run FVT
2. see new `BDS - python bucket` runs

# Screenshots

Screen capture of the new BDS - python log results. 

```
------------------------------------------------------------
           Starting BDS - python_scripts Bucket
------------------------------------------------------------
Thu Oct 17 14:15:29 EDT 2019
------------------------------------------------------------
PRE SETUP: Calling csm_allocation_create:                                                                PASS
allocation_id:  12
Test Case 1 : Calling findJobsRunning.py :                                                               PASS
foundJobs:  0
Clean up allocation:                                                                                     PASS
Validating no active allocations:                                                                        PASS
Test Case 2 : Calling findJobKeys.py :                                                                   PASS
Test Case 3 : Calling findJobMetrics.py :                                                                PASS
Test Case 3a: Calling findJobMetrics.py without required fields:                                         PASS
Test Case 4 : Calling findJobsInRange.py :                                                               PASS
Test Case 5 : Calling findJobTimeRange.py :                                                              PASS
Test Case 5a: Calling findJobTimeRange.py without either allocation_id or job_id:                        PASS
Test Case 6 : Calling findUserJobs.py :                                                                  PASS
Test Case 6a: Calling findUserJobs.py without required field -u user:                                    PASS
Test Case 7 : Calling findWeightedErrors.py :                                                            PASS
Test Case 7a: Calling findWeightedErrors.py without --errormap required field:                           PASS
------------------------------------------------------------
          BDS - python_scripts Bucket Passed
------------------------------------------------------------
Additional Flags:

------------------------------------------------------------
```

### CODE REVIEW

**Comment by williammorrison2** [comment]
Ran the full FVT regression suite against this PR. All the test cases pass including the new BDS ones.
```
------------------------------------------------------------
           Starting BDS - python_scripts Bucket
------------------------------------------------------------
Thu Oct 17 14:15:29 EDT 2019
------------------------------------------------------------
PRE SETUP: Calling csm_allocation_create:                                                                PASS
allocation_id:  12
Test Case 1 : Calling findJobsRunning.py :                                                               PASS
foundJobs:  0
Clean up allocation:                                                                                     PASS
Validating no active allocations:                                                                        PASS
Test Case 2 : Calling findJobKeys.py :                                                                   PASS
Test Case 3 : Calling findJobMetrics.py :                                                                PASS
Test Case 3a: Calling findJobMetrics.py without required fields:                                         PASS
Test Case 4 : Calling findJobsInRange.py :                                                               PASS
Test Case 5 : Calling findJobTimeRange.py :                                                              PASS
Test Case 5a: Calling findJobTimeRange.py without either allocation_id or job_id:                        PASS
Test Case 6 : Calling findUserJobs.py :                                                                  PASS
Test Case 6a: Calling findUserJobs.py without required field -u user:                                    PASS
Test Case 7 : Calling findWeightedErrors.py :                                                            PASS
Test Case 7a: Calling findWeightedErrors.py without --errormap required field:                           PASS
------------------------------------------------------------
          BDS - python_scripts Bucket Passed
------------------------------------------------------------
Additional Flags:

------------------------------------------------------------
```

**Comment by williammorrison2** [comment]
@NickyDaB  Actually just caught something.........we need to change the permission on the `python_scripts.sh` from `-rw-r--r--` to `-rwxr-xr-x`

This output was at the end of the regression run
```
./tools/complete_fvt.sh: line 82: /u/wcmorris/CAST/csmtest/buckets/BDS/python_scripts.sh: Permission denied
```
Other than that it all looks good.

**Comment by NickyDaB** [comment]
try it now

**Comment by williammorrison2** [comment]
OK so after a couple minor tweaks I think this PR is ready to be merged into master. It passes the full regression run. Here is the output.
```
------------------------------------------------------------
           Starting BDS - python_scripts Bucket
------------------------------------------------------------
Fri Oct 18 12:32:27 EDT 2019
------------------------------------------------------------
Set Compute Nodes to (IN_SERVICE): Calling update_computes_in_service:                                   PASS
PRE SETUP: Calling csm_allocation_create:                                                                PASS
allocation_id:  10
Test Case 1 : Calling findJobsRunning.py :                                                               PASS
foundJobs:  0
Clean up allocation:                                                                                     PASS
Validating no active allocations:                                                                        PASS
Test Case 2 : Calling findJobKeys.py :                                                                   PASS
Test Case 3 : Calling findJobMetrics.py :                                                                PASS
Test Case 3a: Calling findJobMetrics.py without required fields:                                         PASS
Test Case 4 : Calling findJobsInRange.py :                                                               PASS
Test Case 5 : Calling findJobTimeRange.py :                                                              PASS
Test Case 5a: Calling findJobTimeRange.py without either allocation_id or job_id:                        PASS
Test Case 6 : Calling findUserJobs.py :                                                                  PASS
Test Case 6a: Calling findUserJobs.py without required field -u user:                                    PASS
Test Case 7 : Calling findWeightedErrors.py :                                                            PASS
Test Case 7a: Calling findWeightedErrors.py without --errormap required field:                           PASS
------------------------------------------------------------
          BDS - python_scripts Bucket Passed
------------------------------------------------------------
Additional Flags:

------------------------------------------------------------
```

**Comment by NickyDaB** [comment]
We approved this pull request on our weekly call. Pulling in.

**Pull request merged**
