### PR TITLE
removed ability to update certain fields via API

### PR DESCRIPTION
**Pull request by NickyDaB**
**Summary:**
- CSM API: csm_ib_cable_update
- addressing defect notes of issue
- tested. seems to be working as expected now.
- user no longer able to update these fields.

Reason for pull request: 
- https://github.com/NickyDaB/CAST/issues/13
- development found defect

### CODE REVIEW

**Comment by pdlun92** [comment]
Passed regression for me too, gonna run some unit tests to be thorough.  Should be done shortly

**Comment by NickyDaB** [comment]
@pdlun92  should be addressed now. check it out.

**Comment by NickyDaB** [comment]
looks like there were some merge conflicts because two of the pull requests we made touched the same files. looking into manually merging so we don't lose any functionality.

**Comment by pdlun92** [comment]
May have broken something on the manual merge.  On running update...

**Comment by NickyDaB** [comment]
yeah, looks like i messed up the manual merge, and i left both versions of adding in a comment. will remove the old version, test it, then i'll let u know when i push updates.

**Comment by NickyDaB** [comment]
I didn't notice anything else on my machine. It should be good now...I hope.

**Comment by pdlun92** [comment]
Looks good now.  Merge away

**Pull request merged**
