### PR TITLE
Bills db migration 18.0 and more

### PR DESCRIPTION
**Pull request by williammorrison2**
# Purpose
Migrate CSM_DB version from 17.0 to 18.0

Added fields within the CSM DB tables which are a part of the new migration upgrade.

| csm_allocation table | Details
|----------------------|---------------------------------
| core_blink           | boolean     not null,
| COMMENT ON COLUMN    | csm_allocation.core_blink is 'flag indicating whether or not to run a blink operation on allocation cores.';

| csm_allocation_history | Details
|----------------------|---------------------------------
| core_blink           | boolean     not null
| COMMENT ON COLUMN    |csm_allocation_history.core_blink is 'flag indicating whether or not to run a blink operation on allocation cores.';

| csm_switch_inventory | Details
|----------------------|---------------------------------
| type                 | text,
| fw_version           | text,
| COMMENT ON COLUMN    | csm_switch_inventory.type is 'The category of this piece of hardware inventory. For example: "FAN", "PS", "SYSTEM", or "MGMT".';
| COMMENT ON COLUMN    | csm_switch_inventory.fw_version is 'The firmware version on this piece of inventory.';

| csm_switch_inventory_history | Details
|----------------------|---------------------------------
| archive_history_time | timestamp,
| type                 | text,
| fw_version           | text
| COMMENT ON COLUMN    | csm_switch_inventory_history.type is 'The category of this piece of hardware inventory. For example: "FAN", "PS", "SYSTEM", or "MGMT".';
| COMMENT ON COLUMN    |csm_switch_inventory_history.fw_version is 'The firmware version on this piece of inventory.';

# How to Test
1. Run regression against the new changes.
2. Additional testing from previous version to ensure the DB migrates to 18.0 with all other version upgrades along the way.
example running from versions
15.0 (schema version (ga_release)) which include updates from 15.1, 16.0, 16.1, 16.2, 17.0 and then -----> 18.0
15.1 (schema version) which include updates from 16.0, 16.1, 16.2, 17.0 and then -----> 18.0
16.0 (schema version) which include updates from 16.1, 16.2, 17.0 and then -----> 18.0
16.1 (schema version) which include updates from 16.2, 17.0 and then -----> 18.0
16.2 (schema version) which include updates from 17.0 and then -----> 18.0
17.0 (schema version) -----> 18.0

# Supporting Documentation
Migration script 18.0 (Read the docs section)
Additional Function and Triggers chart in the (csm_db_appendix.rst page)

## To Do
_Make sure you attempted to do the following:_
- [ ] @pdlun92 (check regression)
- [x] @NickyDaB (code review)
- [ ] @fpizzano  (review)
- [x] @mew2057  (update csm_allocation API with core_blink field option/ test/ and review)

### CODE REVIEW

**Comment by mew2057** [comment]
@pdlun92 I didn't get a chance to run the tests (my dev environment is down atm). I think I caught everything for the changes. If regression fails just slack me the node it failed on and I'll throw together a fix when I'm in office in about an hour.

**Comment by NickyDaB** [comment]
Did `(code review)` but there were a lot of files changed... might have missed something. Overall I think it looks good.

**Comment by pdlun92** [comment]
still getting a db error
```
[root@c650mnp05 basic]# /opt/ibm/csm/bin/csm_allocation_create -j 1 -n c650f03p07
[csmapi][warning]	/u/plundgr/CAST/csmi/src/common/src/csmi_common_utils.c-147: the Error Flag Set
[csmapi][error]	csmi_sendrecv_cmd failed: 25 - csm_allocation_create[52652224]; Database Error Message: syntax error at or near "$30"
/opt/ibm/csm/bin/csm_allocation_create FAILED: returned: 25, errcode: 25 errmsg: csm_allocation_create[52652224]; Database Error Message: syntax error at or near "$30"
```

**Comment by NickyDaB** [comment]
looks like merging in that other pull request created a merge conflict. in switch connector. let me resolve it before we merge this pull request in

**Comment by NickyDaB** [comment]
manually fixed conflict. basically a "merge using mine" aka. use the updates on this branch.

**Comment by mew2057** [comment]
@pdlun92 major my  bad on this one, missed a comma,

**Pull request merged**
