### PR TITLE
Feature: transaction log

### PR DESCRIPTION
**Pull request by mew2057**
Added a transaction log and `BDS logger` to CSM which logs a transaction log formatted using JSON in a format that's easily ingestible by a Big Data Store. Additionally, fixes a bug in state transitions exposed by the transaction log (Issue #92).

This feature is enabled in the configuration file `log` section:

``` JSON
             "bds"                : true,
             "bds_file"           : "/var/log/ibm/csm/csm_transaction.log",
             "bds_rotation_size"  : 1000000000
```

### CODE REVIEW

**Comment by mew2057** [comment]
Think I might refactor `BDS` to be `transaction` before merging since `BDS` isn't strictly accurate.

**Comment by mew2057** [comment]
@pdlun92 looks like the merge killed it.

**Comment by mew2057** [comment]
Wrapped a quick refactor in, renamed `bds` to `transaction`.

@pdlun92 should be good now.

``` JSON
"transaction"               :   true,
 "transaction_file"          :   "/var/log/ibm/csm/csm_transaction.log",
 "transaction_rotation_size" :   1000000000

```

**Comment by pdlun92** [comment]
Build error fix worked, will run regression + the #92 unit tests and report back shortly

**Comment by pdlun92** [comment]
@mew2057 well, THAT build error fix worked...
got a new one
```
 67%] Building CXX object csmd/src/daemon/src/CMakeFiles/csmd.dir/csmi_request_handler/CSMIAllocationCreate.cc.o
/u/plundgr/CAST/csmd/src/daemon/src/csmi_request_handler/CSMIAllocationCreate.cc:30:47: fatal error: csmi/src/common/include/csmi_json.h: No such file or directory
 #include "csmi/src/common/include/csmi_json.h"
                                               ^
compilation terminated.
make[2]: *** [csmd/src/daemon/src/CMakeFiles/csmd.dir/csmi_request_handler/CSMIAllocationCreate.cc.o] Error 1
make[1]: *** [csmd/src/daemon/src/CMakeFiles/csmd.dir/all] Error 2
make: *** [all] Error 2
*** CONFIGURE FAILED  (cmd= make package noinstall   rc=512)
```
suspect that's also a merge fatality?

**Comment by mew2057** [comment]
@pdlun92 Nope, just missed a file.

**Comment by pdlun92** [comment]
Passes regression as well as the unit tests for the allocation state bug fix as described in #92

**Pull request merged**
